<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Gambar Monitor</name>
   <tag></tag>
   <elementGuidId>011add28-574e-4f99-a51c-8653422952cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbodyid']/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tbodyid >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fc7c2e7e-2216-47b3-877b-c84cc609d615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top img-fluid</value>
      <webElementGuid>8b12dee7-3d63-49e9-9ca4-9d67040a338f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>imgs/apple_cinema.jpg</value>
      <webElementGuid>e092b002-77e2-4b42-9240-23b6f5c604e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbodyid&quot;)/div[@class=&quot;col-lg-4 col-md-6 mb-4&quot;]/div[@class=&quot;card h-100&quot;]/a[1]/img[@class=&quot;card-img-top img-fluid&quot;]</value>
      <webElementGuid>bb6f3179-1625-46cd-8260-7af677ef3068</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbodyid']/div/div/a/img</value>
      <webElementGuid>fbe91b0b-3d0a-4667-9acb-0190f9ea373c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>8cc4321f-d498-42f1-a3f4-da201d2f92d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'imgs/apple_cinema.jpg']</value>
      <webElementGuid>3762744a-a613-4eec-bed6-17e7206f3ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
